global_options:
  freezed:freezed:
    runs_before:
      - hive_generator:hive_generator
targets:
  $default:
    builders:
      freezed:
        options:
          map: false
          when: false
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - unused_element
