targets:
  $default:
    builders:
      freezed:
        options:
          map: false
          when: false
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - unused_element
            - library_private_types_in_public_api
