name: wear_tasks
description: A minimal WearOS App to create etesync reminders.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  collection: ^1.18.0
  drift: ^2.15.0
  etebase_flutter: ^1.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.0
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.9
  icalendar: ^0.1.3
  logging: ^1.2.0
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.3
  settings_annotation: ^1.0.1
  sqlite3_flutter_libs: ^0.5.19+1
  uuid: ^4.3.3
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.6.0
  drift_dev: ^2.15.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  settings_builder: ^1.1.1

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#673ab7"
  image: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android_12:
    color: "#673ab7"
