name: wear_tasks
description: A minimal WearOS App to create etesync reminders.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  etebase_flutter: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.5.7
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.6.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
