name: wear_tasks
description: A minimal WearOS App to create etesync reminders.
publish_to: none
version: 1.0.5

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

platforms:
  android:

dependencies:
  collection: ^1.18.0
  drift: ^2.15.0
  etebase_flutter: ^1.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  hooks_riverpod: ^2.4.10
  icalendar: ^0.1.3
  logging: ^1.2.0
  package_info_plus: ^5.0.1
  path: ^1.9.0
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.4
  sentry_flutter: ^7.16.1
  sentry_logging: ^7.16.1
  settings_annotation: ^1.0.1
  sqlcipher_flutter_libs: ^0.6.1
  sqlite3: ^2.4.0
  uuid: ^4.3.3
  wearable_rotary: ^2.0.2
  workmanager: ^0.5.2

dev_dependencies:
  build_runner: ^2.4.8
  cider: ^0.2.6
  custom_lint: ^0.6.2
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.6.2
  drift_dev: ^2.15.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  sentry_dart_plugin: ^1.7.1
  settings_builder: ^1.1.1

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#000000"
  image: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android_12:
    color: "#000000"

pigeon:
  main-input:
    one-language: true
    input: pigeons/
    dart:
      out: lib/gen/pigeons
    kotlin:
      out: android/app/src/main/kotlin/de/skycoder42/wearTasks
      package: de.skycoder42.wearTasks
  inputs:
    - input: rotary_input.dart
      dart:
        out: rotary_input.pigeon.dart
      kotlin:
        out: RotaryInput.pigeon.kt

sentry:
  upload_debug_symbols: true
  org: skycoder42
  project: wear_tasks

cider:
  link_template:
    tag: https://github.com/Skycoder42/wear_tasks/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/wear_tasks/compare/v%from%...v%to%
