name: CI/CD for wear_tasks

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    with:
      unitTestPaths: ""
      buildRunner: true

  cd:
    name: CD
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - name: Install JDK Version 17
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Install Flutter-SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Download flutter binary artifacts
        run: flutter precache --universal --android
      - name: Validate flutter setup
        run: flutter doctor -v
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Restore dart packages
        run: flutter pub get
      - name: Create build files
        run: flutter pub run build_runner build
      - name: Build android app bundle
        run: >-
          flutter build appbundle
          --release
          --build-number TODO
          --obfuscate
          --split-debug-info=build/debug-info
          --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }}
      - name: Upload app and debug info
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/debug-info
          retention-days: 1
          if-no-files-found: error
